-- Run integration creation using ACCOUNTADMIN.
-- Replace the role ARN locally before execution.
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION NOVACART_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN =
        'arn:aws:iam::<AWS_ACCOUNT_ID>:role/NovaCartSnowflakeS3Role'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://novacart-customer-360-peter-2026/raw/'
    );

GRANT USAGE
ON INTEGRATION NOVACART_S3_INTEGRATION
TO ROLE NOVACART_ENGINEER;

USE ROLE NOVACART_ENGINEER;
USE DATABASE NOVACART_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT NOVACART_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    ENCODING = 'UTF8';

CREATE OR REPLACE STAGE NOVACART_S3_STAGE
    URL = 's3://novacart-customer-360-peter-2026/raw/'
    STORAGE_INTEGRATION = NOVACART_S3_INTEGRATION
    FILE_FORMAT = NOVACART_CSV_FORMAT
    DIRECTORY = (ENABLE = TRUE);
